### ISSUE TITLE
eval_default is not consistent with other chunk default options

### ISSUE THREAD

**Issue by kiwi0fruit** [pystitch/stitch#66]
It would be nice to have:
```yaml
---
chunk-defaults:
    eval: false
    echo: false
...
```
In this case we do not need `eval_default` anymore.

## UPD 

Default chunk options are already in Stitch. See discussion below. But `eval_default` is not consistent with other default options names (and implementation also inconsistent).
